version: '3.6'
services:
  exb:
    container_name: exb
    image: exb
    env_file: .env
    environment:
      VIRTUAL_HOST: ${EXB_VIRTUAL_HOST}
      VIRTUAL_PORT: 3001
      NETWORK_ACCESS: internal
#      LETSENCRYPT_HOST: ${EXB_VIRTUAL_HOST}
#      LETSENCRYPT_MAIL: ${MY_EMAIL}
    networks:
      - proxy_net
    ports:
      - 3001:3001
#    volumes:
#
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
   
#volumes:
#
networks:
  # This is a network we share with our reverse proxy
  proxy_net:
    # Won't be created or destroyed with docker-compose up|down
    external: true
