version: '3.6'
services:
  exb:
    container_name: exb
    image: exb
    env_file: .env
    environment:
      VIRTUAL_HOST: ${EXB_VIRTUAL_HOST}
      VIRTUAL_PORT: 3000
      NETWORK_ACCESS: internal
#      LETSENCRYPT_HOST: ${EXB_VIRTUAL_HOST}
#      LETSENCRYPT_MAIL: ${MY_EMAIL}
    networks:
      - proxy_net
    expose:
      - 3000
    ports:
      - 3001:3001
    volumes:
      - exb_public:/home/node/server/src/public
    restart: unless-stopped
    build:
      args:
        snapshot: ArcGISExperienceBuilder
      context: .
      dockerfile: Dockerfile
   
volumes:
  exb_public:
    name: exb_public
  exb_widgets:
    name: exb_widgets
    
networks:
  # This is a network we share with our reverse proxy
  proxy_net:
    # Won't be created or destroyed with docker-compose up|down
    external: true
