version: '3.7'
    
services:
  server:
    image: exb-server
    env_file: .env
    environment:
#      VIRTUAL_HOST: ${EXB_VIRTUAL_HOST}
#      VIRTUAL_PORT: 3000
      NETWORK_ACCESS: internal
#      LETSENCRYPT_HOST: ${EXB_VIRTUAL_HOST}
#      LETSENCRYPT_MAIL: ${MY_EMAIL}
    ports:
      #http://cc-testmaps:3000
      - 3000:3000
      # https://cc-testmaps:3001
      - 3001:3001
    volumes:
      - ./public:/home/node/server/public
    build:
      context: .
      dockerfile: Dockerfile.server
    command: ["npm", "start"]
    # command: node src/server.js

    # for docker-compose
    restart: unless-stopped
    
  client:
    image: exb-client
    volumes:
      - ./public:/home/node/server/public
    build:
      context: .
      dockerfile: Dockerfile.client
    command: ["npm", "start"]
   
    # for docker-compose
    restart: unless-stopped