version: "3.9"

networks:
  proxy:
    name: ${NETWORK_NAME}
    external: true

services:
  server:
    image: exb-server
    env_file: .env
    environment:
      NETWORK_ACCESS: internal
    ports:
      #http://cc-testmaps:3000
      - 3000:3000
      # https://cc-testmaps:3001
      - 3001:3001
    volumes:
      - ./public:/home/node/server/public
    build:
      context: .
      dockerfile: Dockerfile.server
    command: ["npm", "start"]
    # command: node src/server.js
    networks:
      proxy:
        aliases:
          - exb
    restart: unless-stopped
    
  client:
    image: exb-client
    volumes:
      - ./public:/home/node/server/public
      - ./client-extensions:/home/node/client/your-extensions
    build:
      context: .
      dockerfile: Dockerfile.client
    command: ["npm", "start"]
    restart: unless-stopped
