FROM node:12
LABEL maintainer="Brian H Wilson brian@wildsong.biz"

USER node
WORKDIR /home/node
ADD --chown=node ./ArcGISExperienceBuilder/ /home/node/

WORKDIR /home/node/client
RUN npm ci && npm audit fix

