FROM node:12
LABEL maintainer="Brian H Wilson brian@wildsong.biz"

USER node
WORKDIR /home/node
ADD --chown=node ./ArcGISExperienceBuilder/ .

RUN mkdir -p server/public
#VOLUME /home/node/server/src/public

WORKDIR /home/node/server/
RUN npm ci && npm audit fix
