FROM node:18
LABEL maintainer="Brian H Wilson brian@wildsong.biz"

USER node
WORKDIR /home/node
ADD --chown=node ./ArcGISExperienceBuilder/ /home/node/

VOLUME /home/node/client/your-extensions

WORKDIR /home/node/client

RUN npm install
# The package 'quill' breaks this
#RUN npm audit fix --omit=dev
