version: '3.7'
    
services:
  server:
    image: exb-server
    env_file: .env
    environment:
#      VIRTUAL_HOST: ${EXB_VIRTUAL_HOST}
#      VIRTUAL_PORT: 3000
      NETWORK_ACCESS: internal
#      LETSENCRYPT_HOST: ${EXB_VIRTUAL_HOST}
#      LETSENCRYPT_MAIL: ${MY_EMAIL}
    ports:
      # https://cc-testmaps:3001
      - 3001:3001
    volumes:
      - ./public:/home/node/ArcGISExperienceBuilder/server/public
    build:
      context: .
      args:
        snapshot: arcgis-experience-builder-1.7.zip
      dockerfile: Dockerfile.server
    command: ["npm", "start"]
    # command: node src/server.js
        
  client:
    image: exb-client
    env_file: .env
    environment:
#      VIRTUAL_HOST: ${EXB_VIRTUAL_HOST}
#      VIRTUAL_PORT: 3000
      NETWORK_ACCESS: internal
#      LETSENCRYPT_HOST: ${EXB_VIRTUAL_HOST}
#      LETSENCRYPT_MAIL: ${MY_EMAIL}
    #ports:
      # https://cc-testmaps:3001
#      - 3001:3001
    volumes:
      - ./public:/home/node/ArcGISExperienceBuilder/server/public
    build:
      context: .
      args:
        snapshot: arcgis-experience-builder-1.7.zip
      dockerfile: Dockerfile.client
    command: ["npm", "start"]
   
